# Generated by Django 4.1 on 2022-08-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=500)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
    ]
